services:

  Aboalarm\LoggerPhp\Logger\Logger:
    autowire: true
    public: true
    arguments:
      -
        graylog_host: '%env(LOGGING_GRAYLOG_HOST)%'
        graylog_port: '%env(LOGGING_GRAYLOG_PORT)%'
        logger_name: '%env(LOGGING_LOGGER_NAME)%'
        logger_min_log_level: '%env(LOGGING_LOGGER_MIN_LOG_LEVEL)%'
        logger_enable_queue: '%env(LOGGING_LOGGER_ENABLE_QUEUE)%'
        logger_queue: '%env(LOGGING_LOGGER_QUEUE)%'
        logger_env: '%env(APP_ENV)%'
      - 'symfony'
    calls:
      - [ setMessageBus, ['@messenger.bus.default']]
      - [ setSymfonyRequestStack, ['@request_stack']]


  Aboalarm\LoggerPhp\Symfony\MessageHandler\LogMessageHandler:
    tags: [messenger.message_handler]
